DATA_BLOCK DbDebug // ¬ременные переменные дл€ отладки.

AUTHOR : VA
FAMILY : LIB_PLC

// ќбъ€вление переменных.
STRUCT
OB82_CNT_ERR      :DINT          := L#0                       ; // —четчик вызовов обработчика ошибок OB82.
OB83_CNT_ERR      :DINT          := L#0                       ; // —четчик вызовов обработчика ошибок OB83.
OB86_CNT_ERR      :DINT          := L#0                       ; // —четчик вызовов обработчика ошибок OB86.
OB122_CNT_ERR     :DINT          := L#0                       ; // —четчик вызовов обработчика ошибок OB122.
DebugBool0        :BOOL          := FALSE                     ; // 1 бит.
DebugBool1        :BOOL          := FALSE                     ; // 1 бит.
DebugBool2        :BOOL          := FALSE                     ; // 1 бит.
DebugBool3        :BOOL          := FALSE                     ; // 1 бит.
DebugBool4        :BOOL          := FALSE                     ; // 1 бит.
DebugBool5        :BOOL          := FALSE                     ; // 1 бит.
DebugBool6        :BOOL          := FALSE                     ; // 1 бит.
DebugBool7        :BOOL          := FALSE                     ; // 1 бит.
DebugByte0        :BYTE          := B#16#00                   ; // 8 бит.
DebugByte1        :BYTE          := B#16#00                   ; // 8 бит.
DebugByte2        :BYTE          := B#16#00                   ; // 8 бит.
DebugByte3        :BYTE          := B#16#00                   ; // 8 бит.
DebugWord0        :WORD          := W#16#0000                 ; // 16 бит.
DebugWord1        :WORD          := W#16#0000                 ; // 16 бит.
DebugWord2        :WORD          := W#16#0000                 ; // 16 бит.
DebugWord3        :WORD          := W#16#0000                 ; // 16 бит.
DebugDword0       :DWORD         := DW#16#00000000            ; // 32 бит.
DebugDword1       :DWORD         := DW#16#00000000            ; // 32 бит.
DebugDword2       :DWORD         := DW#16#00000000            ; // 32 бит.
DebugDword3       :DWORD         := DW#16#00000000            ; // 32 бит.
DebugReal0        :REAL          := 0.0                       ; // 32 бит.
DebugReal1        :REAL          := 0.0                       ; // 32 бит.
DebugReal2        :REAL          := 0.0                       ; // 32 бит.
DebugReal3        :REAL          := 0.0                       ; // 32 бит.
DebugInt0         :INT           := 0                         ; // 16 бит.
DebugInt1         :INT           := 0                         ; // 16 бит.
DebugInt2         :INT           := 0                         ; // 16 бит.
DebugInt3         :INT           := 0                         ; // 16 бит.
DebugDint0        :DINT          := L#0                       ; // 32 бит.
DebugDint1        :DINT          := L#0                       ; // 32 бит.
DebugDint2        :DINT          := L#0                       ; // 32 бит.
DebugDint3        :DINT          := L#0                       ; // 32 бит.
DebugTime         :TIME          := T#0d0h0m0s000ms           ; // 32 бит.
DebugS5Time       :S5TIME        := S5T#0h0m0s0ms             ; // 16 бит.
DebugDate         :DATE          := D#1999-12-31              ; // 16 бит.
DebugTimeOfDay    :TIME_OF_DAY   := TOD#23:59:59.999          ; // 32 бит.
DebugDateAndTime  :DATE_AND_TIME := DT#1999-12-31-23:59:59.999; // 64 бит.
DebugChar         :CHAR          := 'i'                       ;
DebugString       :STRING        := 'DIY.PLC.314@gmail.com, https://github.com/DIYPLC/LIB_PLC, License GNU GPL'; // —ообщение дл€ реверс инженеров.
DebugBitArray     :ARRAY [0..7] OF BOOL; // 8*1 бит.
DebugRealArray    :ARRAY [0..7] OF REAL; // 32*8 бит.
END_STRUCT

// »нициализаци€ массивов.
BEGIN
DebugBitArray[0]:=FALSE; 
DebugBitArray[1]:=FALSE; 
DebugBitArray[2]:=FALSE; 
DebugBitArray[3]:=FALSE; 
DebugBitArray[4]:=FALSE; 
DebugBitArray[5]:=FALSE; 
DebugBitArray[6]:=FALSE; 
DebugBitArray[7]:=FALSE; 
DebugRealArray[0]:=0.0; 
DebugRealArray[1]:=0.0; 
DebugRealArray[2]:=0.0; 
DebugRealArray[3]:=0.0; 
DebugRealArray[4]:=0.0; 
DebugRealArray[5]:=0.0; 
DebugRealArray[6]:=0.0; 
DebugRealArray[7]:=0.0; 
END_DATA_BLOCK

// @COPYLEFT ALL WRONGS RESERVED :)
// Author: VA
// Contacts: DIY.PLC.314@gmail.com
// Date start LIB_PLC: 2014
// License: GNU GPL-2.0-or-later
// https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
// https://www.youtube.com/watch?v=n1F_MfLRlX0
// https://www.youtube.com/@DIY_PLC
// https://github.com/DIYPLC/LIB_PLC
// https://oshwlab.com/diy.plc.314/PLC_HW1_SW1
// https://3dtoday.ru/3d-models/mechanical-parts/body/korpus-na-din-reiku
// https://t.me/DIY_PLC
