//Порядок компиляции всех файлов в проекте имеет огромное значение и описан в данном файле.

//Бибилиотека блоков для ПЛК LibPlc.
// LibPlc блоки из теории управления.
FbPIDcontrol       //LibPlc Регулятор ПИД.
FbScale            //LibPlc Линейное преобразование.
FbFilterA          //LibPlc Апериодическое звено первого порядка.
FbDeriveF          //LibPlc Производная с фильтрацией.
FbDelayN           //LibPlc Задержка на N тактов.
FbIntegrator       //LibPlc Интегратор W(s)=1/s.
FbLimit            //LibPlc Амплитудный ограничитель.
FbDeadBand         //LibPlc Зона нечувствительности.
Fb2PosControl      //LibPlc Регулятор двухпозиционный.
Fb3PosControl      //LibPlc Регулятор трехпозиционный.
FbStpForPD         //LibPlc Аналоговый ПД- регулятор превращаем в дискретный.
FbVirtualMotorGear //LibPlc Виртуальный МЭО для отладки шагового регулятора.
// LibPlc Вспомогательные блоки для ПИД- регулятора.
FbRamp             //LibPlc Рампа разгона торможения.
FbGSS              //LibPlc Генератор сигналов и псевдослучайных чисел.
FbAlarm            //LibPlc Сигнализатор аварийного уровня сигнала.
FbFilterNaN        //LibPlc Фильтр NaN и Inf для чисел REAL.
FbModeSelector     //LibPlc Переключатель режимов работы.
FbSoftPWM          //LibPlc ШИМ генератор двухканальный.
// LibPlc Базовые дискретные блоки.
FbTriggerRS        //LibPlc Триггер RS.
FbEdgeNeg          //LibPlc Детектор ниспадающего фронта.
FbEdgePos          //LibPlc Детектор нарастающего фронта.
FbTimerTof         //LibPlc Таймер TOF.
FbTimerTon         //LibPlc Таймер TON.
FbWordToBits       //LibPlc Преобразование слова в 16 бит.
FbBitsToWord       //LibPlc Преобразование 16 бит в слово.
// LibPlc Технологические блоки.
FbMotor            //LibPlc Двигатель с частотником и контактором.
FbValve            //LibPlc Пневмоцилиндр с коцевиками.
FbCounter          //LibPlc Счетчик импульсов.
// LibPlc платформозависимые блоки SIEMENS.
FbDriverAi420      //LibPlc Драйвер аналогово входа 4...20мА.
FbDriverAo420      //LibPlc Драйвер аналогово выхода 4...20мА.

//Блоки данных для сопряжения с SCADA HMI.
//При компиляции блоков данных возможна потеря технологических значений переменных в блоках данных.
//Для сохранения данных истользовать VAT таблицу ReadBack.
DbHmi1PIRCA1 //ПИД- регулятор давления.
DbDebug      //Временные переменные для отладки.

//Технологические программы.
Fb1PIRCA1 //ПИД- регулятор давления.

//Компилируем блоки данных.
DbInstance //Файл генерирует блоки данных к функциональным блокам.

//Задачи для вызова технологисеских программ.
FbTaskCyclic //Задача вызывается циклически.
FbTask100ms  //Задача вызывается каждые 100ms.
DbTask       //Блоки данных для задач.

//Системные call back.
OB1   //Cycle Execution
OB35  //Cyclic Interrupt 5
OB100 //Complete Restart

//  +---------+
//  | GNU GPL |
//  +---------+
//  |
//  |
//  .= .-_-. =.
// ((_/)o o(\_))
//  `-'(. .)`-'
//  |/| \_/ |\
//  ( |     | )
//  /"\_____/"\
//  \__)   (__/
// @COPYLEFT ALL WRONGS RESERVED :)
// Author: VA
// Contacts: DIY.PLC.314@gmail.com
// License: GNU GPL v2
