//Порядок компиляции всех файлов в проекте имеет огромное значение и описан в данном файле.

{//Опции компилятора SCL.
//Данные опции почему то не работают в исходниках, а тут работают.
GenerateReferenceData := 'y' ; //SCL: Генерировать перекрестные ссылки.
CreateDebugInfo       := 'y' ; //SCL: Генерировать оладочную информацию.
SetOKFlag             := 'y' ; //SCL: ENO = 1
MonitorArrayLimits    := 'y' ; //SCL: Следить за границами массивов.
OptimizeObjectCode    := 'y'   //SCL: Оптимизация объектного кода.
}

//Бибилиотека блоков для ПЛК LIB_PLC.

//Базовые блоки обработки аналоговых сигналов, упорядочил по частоте использования.
FbPIDcontrol       //LIB_PLC Регулятор ПИД.
FbPIDstep          //LIB_PLC ПИД- регулятор с двумя дискретными выходами.
FbStpForPD         //LIB_PLC Аналоговый ПД- регулятор превращаем в дискретный ПИ.
Fb2PosControl      //LIB_PLC Регулятор двухпозиционный.
Fb3PosControl      //LIB_PLC Регулятор трехпозиционный.
FbScale            //LIB_PLC Линейное преобразование.
FbLimit            //LIB_PLC Амплитудный ограничитель.
FbRamp             //LIB_PLC Рампа разгона торможения.
FbFilterA          //LIB_PLC Апериодическое звено первого порядка.
FbFilterM          //LIB_PLC Фильтр медианный.
FbDeriveF          //LIB_PLC Производная с фильтрацией.
FbGSS              //LIB_PLC Генератор сигналов и псевдослучайных чисел.
FbAlarm            //LIB_PLC Сигнализатор аварийного уровня сигнала.
FbDispersion       //LIB_PLC Дисперсия PV.
FbFilterNaN        //LIB_PLC Фильтр NaN и Inf для чисел REAL.
FbSoftPWM          //LIB_PLC ШИМ генератор двухканальный.
FbDelayN           //LIB_PLC Задержка на N тактов.
FbIntegrator       //LIB_PLC Интегратор W(s)=1/s.
FbDeadBand         //LIB_PLC Зона нечувствительности.
FbS5TimeToReal     //LIB_PLC Конвертор S5TIME в милисекунды.

//Базовые дискретные блоки, упорядочил по частоте использования.
FbModeSelector     //LIB_PLC Переключатель режимов работы.
FbTriggerRS        //LIB_PLC Триггер RS.
FbEdgeNeg          //LIB_PLC Детектор ниспадающего фронта.
FbEdgePos          //LIB_PLC Детектор нарастающего фронта.
FbTON              //LIB_PLC Таймер TON.
FbTOF              //LIB_PLC Таймер TOF.
FbWordToBits       //LIB_PLC Преобразование слова в 16 бит.
FbBitsToWord       //LIB_PLC Преобразование 16 бит в слово.
FbBlink            //LIB_PLC Мигающий светодиод.
FbSum1bit          //LIB_PLC Сумматор 1бит.
FbCounter          //LIB_PLC Счетчик импульсов.

//Блоки для конкретных технологических железок.
FbMotor            //LIB_PLC Двигатель с частотником и контактором.
FbValve            //LIB_PLC Пневмоцилиндр с коцевиками.
FbPIDsteam         //LIB_PLC ПИД-регулятор давления пара быстромедленный.
FbSimMotorGear     //LIB_PLC Виртуальный МЭО для отладки шагового регулятора.

//Платформозависимые блоки SIEMENS.
FbDriverAi420      //LIB_PLC Драйвер аналогово входа 4...20мА.
FbDriverAo420      //LIB_PLC Драйвер аналогово выхода 4...20мА.
FbDriverDi         //LIB_PLC Драйвер дискретного входа.
FbDriverDo         //LIB_PLC Драйвер дискретного выхода.
FbDriverFRA        //LIB_PLC Управление приводом MITSUBISHI FR-A740, FR-A840 по PROFIBUS PD.
FbDriverMM440PPO3  //LIB_PLC Управление приводом SIEMENS MICROMASTER 440 по PROFIBUS PD.
FbDriverAD800PPO4  //LIB_PLC Управление приводом OPTUMUS DRIVE AD800 по PROFIBUS PD.

//Блоки зависимые от компилятора CFC PCS7.
FbOsBoolPls        //LIB_PLC WinCC interface CFC PCS7.
FbOsBool           //LIB_PLC WinCC interface CFC PCS7.
FbOsReal           //LIB_PLC WinCC interface CFC PCS7.
FbOsInt            //LIB_PLC WinCC interface CFC PCS7.
FbOsDint           //LIB_PLC WinCC interface CFC PCS7.
FbOsWord           //LIB_PLC WinCC interface CFC PCS7.
FbOsDword          //LIB_PLC WinCC interface CFC PCS7.
FbSampleTime       //LIB_PLC Шаг дискретизации по времени CFC PCS7.
FbSubstReal        //LIB_PLC Замещение аналогово сигнала для PCS7v9.

//Блок зависит от SFC6 RD_SINFO SFB5 TOF
FbReset            //LIB_PLC Флаг первого скана с TOF задержкой CFC PCS7.

//Блоки зависят от SFC1 READ_CLK
FbDriverRTC        //LIB_PLC Блок чтения часов реального времени.
FbRunTimeMeter     //LIB_PLC Измерение времени выполнения участка программы.

//Блоки зависят от SFB14 GET SFB15 PUT
FbS7con            //LIB_PLC Обмен данными между двумя ПЛК S7-300(400).
FbS7conRx          //LIB_PLC Данные принятые через S7 connection в NetPro.
FbS7conTx          //LIB_PLC Данные отправленные через S7 connection в NetPro.

//Блоки данных для сопряжения с SCADA HMI.
//При компиляции блоков данных возможна потеря технологических значений переменных в блоках данных.
//Для сохранения данных истользовать VAT таблицу ReadBack.
DbDebug      //Временные переменные для отладки.

//Технологические программы.
Db1PC1Hmi    //1PC1 ПИД- регулятор давления.
Fb1PC1       //1PC1 ПИД- регулятор давления.

//Компилируем блоки данных.
DbInstance   //Файл генерирует блоки данных к функциональным блокам.

//Задачи для вызова технологисеских программ.
FbTaskCyclic //Задача вызывается циклически.
FbTask100ms  //Задача вызывается каждые 100ms.
DbTask       //Блоки данных для задач.

//Системные call back.
OB1   //Cycle Execution
OB35  //Cyclic Interrupt 5
OB100 //Complete Restart

//Обработчики ошибок.
OB82  //I/O Point Fault 1
OB83  //Вызывается если вытаскиваем модули: DI DO AI.
OB86  //Loss of Rack Fault
OB122 //Вызывается если вытаскиваем модули: AO.

//  +---------+
//  | GNU GPL |
//  +---------+
//  |
//  |
//  .= .-_-. =.
// ((_/)o o(\_))
//  `-'(. .)`-'
//  |/| \_/ |\
//  ( |     | )
//  /"\_____/"\
//  \__)   (__/
// @COPYLEFT ALL WRONGS RESERVED :)
// Author: VA
// Contacts: DIY.PLC.314@gmail.com
// Date: 2014 - 2024
// License: GNU GPL-2.0-or-later
// https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
// https://www.youtube.com/watch?v=n1F_MfLRlX0
//
// See also:
// https://www.youtube.com/@DIY_PLC
// https://github.com/DIYPLC/LIB_PLC
// https://oshwlab.com/diy.plc.314/PLC_HW1_SW1
// https://3dtoday.ru/3d-models/mechanical-parts/body/korpus-na-din-reiku
// https://t.me/DIY_PLC
