//Порядок компиляции всех файлов в проекте имеет огромное значение и описан в данном файле.

{//Опции компилятора SCL.
//Данные опции почему то не работают в исходниках, а тут работают.
GenerateReferenceData := 'y' ; //SCL: Генерировать перекрестные ссылки.
CreateDebugInfo       := 'y' ; //SCL: Генерировать оладочную информацию.
SetOKFlag             := 'y' ; //SCL: ENO = 1
MonitorArrayLimits    := 'y' ; //SCL: Следить за границами массивов.
OptimizeObjectCode    := 'y'   //SCL: Оптимизация объектного кода.
}

//Бибилиотека блоков для ПЛК LIB_PLC.
// LIB_PLC блоки из теории управления.
FbPIDcontrol       //LIB_PLC Регулятор ПИД.
FbScale            //LIB_PLC Линейное преобразование.
FbFilterA          //LIB_PLC Апериодическое звено первого порядка.
FbFilterM          //LIB_PLC Фильтр медианный.
FbDeriveF          //LIB_PLC Производная с фильтрацией.
FbDelayN           //LIB_PLC Задержка на N тактов.
FbIntegrator       //LIB_PLC Интегратор W(s)=1/s.
FbLimit            //LIB_PLC Амплитудный ограничитель.
FbDeadBand         //LIB_PLC Зона нечувствительности.
Fb2PosControl      //LIB_PLC Регулятор двухпозиционный.
Fb3PosControl      //LIB_PLC Регулятор трехпозиционный.
FbStpForPD         //LIB_PLC Аналоговый ПД- регулятор превращаем в дискретный ПИ.
FbVirtualMotorGear //LIB_PLC Виртуальный МЭО для отладки шагового регулятора.
// LIB_PLC Вспомогательные блоки для ПИД- регулятора.
FbRamp             //LIB_PLC Рампа разгона торможения.
FbGSS              //LIB_PLC Генератор сигналов и псевдослучайных чисел.
FbAlarm            //LIB_PLC Сигнализатор аварийного уровня сигнала.
FbFilterNaN        //LIB_PLC Фильтр NaN и Inf для чисел REAL.
FbModeSelector     //LIB_PLC Переключатель режимов работы.
FbSoftPWM          //LIB_PLC ШИМ генератор двухканальный.
// LIB_PLC Базовые дискретные блоки.
FbTriggerRS        //LIB_PLC Триггер RS.
FbEdgeNeg          //LIB_PLC Детектор ниспадающего фронта.
FbEdgePos          //LIB_PLC Детектор нарастающего фронта.
FbTimerTof         //LIB_PLC Таймер TOF.
FbTimerTon         //LIB_PLC Таймер TON.
FbWordToBits       //LIB_PLC Преобразование слова в 16 бит.
FbBitsToWord       //LIB_PLC Преобразование 16 бит в слово.
FbBlink            //LIB_PLC Мигающий светодиод.
// LIB_PLC Технологические блоки.
FbMotor            //LIB_PLC Двигатель с частотником и контактором.
FbValve            //LIB_PLC Пневмоцилиндр с коцевиками.
FbPIDsteam         //LIB_PLC ПИД-регулятор давления пара быстромедленный.
FbCounter          //LIB_PLC Счетчик импульсов.
// LIB_PLC платформозависимые блоки SIEMENS.
FbDriverAi420      //LIB_PLC Драйвер аналогово входа 4...20мА.
FbDriverAo420      //LIB_PLC Драйвер аналогово выхода 4...20мА.
FbDriverFRA        //LIB_PLC Управление приводом MITSUBISHI FR-A740, FR-A840 по PROFIBUS PD.

//Блоки данных для сопряжения с SCADA HMI.
//При компиляции блоков данных возможна потеря технологических значений переменных в блоках данных.
//Для сохранения данных истользовать VAT таблицу ReadBack.
DbDebug      //Временные переменные для отладки.

//Технологические программы.
Db1PIRCA1Hmi //1PIRCA1 ПИД- регулятор давления.
Fb1PIRCA1    //1PIRCA1 ПИД- регулятор давления.

//Компилируем блоки данных.
DbInstance //Файл генерирует блоки данных к функциональным блокам.

//Задачи для вызова технологисеских программ.
FbTaskCyclic //Задача вызывается циклически.
FbTask100ms  //Задача вызывается каждые 100ms.
DbTask       //Блоки данных для задач.

//Системные call back.
OB1   //Cycle Execution
OB35  //Cyclic Interrupt 5
OB100 //Complete Restart
//Обработчики ошибок.
OB82  //I/O Point Fault 1
OB83  //Вызывается если вытаскиваем модули: DI DO AI.
OB86  //Loss of Rack Fault
OB122 //Вызывается если вытаскиваем модули: AO.

//  +---------+
//  | GNU GPL |
//  +---------+
//  |
//  |
//  .= .-_-. =.
// ((_/)o o(\_))
//  `-'(. .)`-'
//  |/| \_/ |\
//  ( |     | )
//  /"\_____/"\
//  \__)   (__/
// @COPYLEFT ALL WRONGS RESERVED :)
// Author: VA
// Contacts: DIY.PLC.314@gmail.com
// License: GNU GPL v2
