(*

Библиотека функциональных блоков для ПЛК S7-300,400,1200,1500 STEP7 / PCS7 / TIA Portal.
Самый первый блок FbPIDcontrol.SCL (2014 год) остальное появилось как надстройка вокруг него.
Пример применения библиотеки в файле Fb1PC1.SCL
Данный проект используется как заготовка для других проектов, при этом лишние файлы необходимо удалить.
Данная библиотека разрабатывалась как кросс платформенная.
Блоки можно использовать на ПЛК других производителей.
Так же блоки легко портируются на C/C++ для применения в Arduino и STM32.
Файлы открываются в блокноте notepad windows.

Кодировка текста для STEP7 / PCS7 = ANSI.
Кодировка текста для TIA Portal = UTF8 + BOM.

Дерево вызовов.
OB1.SCL + (OB100.SCL при перезагрузке) //Платформа зависимый уровень.
  |
  +-FbTaskCyclic.SCL //Уровень взаимодействия между частями технологического оборудования и I/O.
    |
    +-Fb1PC1.SCL + Db1PC1Hmi.SCL //Управление конкреным технологическим оборудованием.
      |
      +-FbPIDcontrol.SCL //LIB_PLC библиокека функциональных блоков для ПЛК.

Другие библиотеки для PLC:
http://oscat.de/
https://github.com/simsum/oscat
SIMATIC PCS7 APL
https://web.archive.org/web/20220322174546/http://plc4good.org.ua/view_post.php?id=256
https://github.com/komatic1/SCL_PCS7_AdvLib
https://github.com/komatic1/SCL_regulation_control
https://github.com/eclipse-4diac/4diac-forte/tree/release/src/modules/IEC61131-3/Timers
https://github.com/beremiz/beremiz/blob/python3/plcopen/Additional_Function_Blocks.xml
https://asutp.org/news/library_of_general_functions_lgf_step_7_basic_professional_tia_portal_simatic_s7_1200_s7_1500/2025-11-28-639
https://openplclibrary.com/

Мои источники информации отсортировал по приоритету:
https://en.wikipedia.org/wiki/The_Story_of_Maths
https://en.wikipedia.org/wiki/The_Mechanical_Universe
https://www.youtube.com/@numberphile
https://www.youtube.com/@MATLAB
https://www.youtube.com/@Exponenta-tech
https://www.youtube.com/@%D0%9C%D0%B0%D1%82%D0%BA%D1%83%D0%BB%D1%8C%D1%82-%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%D0%A1%D0%B0%D0%B2%D0%B2%D0%B0%D1%82%D0%B5%D0%B5

https://www.gnu.org/
https://www.youtube.com/@UNEEX_MSU
https://www.youtube.com/@tkhirianov
https://www.youtube.com/@narodstream552
https://www.youtube.com/@Zefar91
https://www.youtube.com/@abglazov
https://www.youtube.com/@VladimirMedintsev

https://www.youtube.com/@AmperkaRuOfficial
https://www.youtube.com/@AlexGyverShow
https://www.youtube.com/@codius
https://www.youtube.com/@ChipDipvideo
https://www.youtube.com/@BachiloDmitry
https://www.youtube.com/@AndreySozykin

https://www.youtube.com/@linkmeup-podcast
https://www.youtube.com/@Plc4goodOrgUa
https://web.archive.org/web/20220322173236/http://plc4good.org.ua/index.php?sub=1
https://github.com/komatic1
https://rutracker.net/forum/index.php
https://plc247.com/

https://www.youtube.com/@ETUSPB

Открытая АСУТП:
https://it.severstal.com/products/oasu-tp/
https://rapidscada.ru/community/

Привод:
https://www.youtube.com/@alekssorokoletov
https://privod.ru/news/video/
https://www.youtube.com/live/_P_BkniH79U?si=xnp8gv-a0i7Yo7cW

  +---------+
  | GNU GPL |
  +---------+
  |
  |
  .= .-_-. =.
 ((_/)o o(\_))
  `-'(. .)`-'
  |/| \_/ |\
  ( |     | )
  /"\_____/"\
  \__)   (__/

*)

// @COPYLEFT ALL WRONGS RESERVED :)
// Author: VA
// Contacts: DIY.PLC.314@gmail.com
// Date start LIB_PLC: 2014
// License: GNU GPL-2.0-or-later
// https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
// https://www.youtube.com/watch?v=n1F_MfLRlX0
// https://www.youtube.com/@DIY_PLC
// https://github.com/DIYPLC/LIB_PLC
// https://oshwlab.com/diy.plc.314/PLC_HW1_SW1
// https://3dtoday.ru/3d-models/mechanical-parts/body/korpus-na-din-reiku
// https://t.me/DIY_PLC
