FUNCTION_BLOCK FbTask100ms //Задача вызывается каждые 100ms.

//      DbTask100ms
//    +-------------+
//    | FbTask100ms |
// ->-|Ts_ms        |
// ->-|Reset        |
//    +-------------+

VAR_INPUT //Входные переменные, не сохраняемые.
Ts_ms :DINT := 100  ; //Шаг дискретизации по времени [мс].
Reset :BOOL := FALSE; //Сброс при перезагрузке.
END_VAR

VAR_OUTPUT //Выходные переменные, не сохраняемые.
END_VAR

;

END_FUNCTION_BLOCK
